print ("Hello World Liubov")
print ()
print ("test")
print ("Hello World", "Text1", "Text2", sep= ",", end="-")
print ("Next step")
# а тут мій коментар
print("Hello\nWorld")
print ("This is again me \n \t Liubov")
print ("The name of the brand is \"Lvivska Kava\"")
print ("To check what we had added")
print ("One more")
print ("One more")
